/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandSlugRouteImport } from './routes/$brandSlug'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminGateRouteImport } from './routes/admin/_gate'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoSplatRouteImport } from './routes/catalogo.$'
import { Route as ConteudoTabacoRouteImport } from './routes/conteudo.tabaco'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal.aviso-legal'
import { Route as LegalPrivacidadeRouteImport } from './routes/legal.privacidade'
import { Route as LegalTermosRouteImport } from './routes/legal.termos'
import { Route as MarcasIndexRouteImport } from './routes/marcas.index'
import { Route as MarcasSlugRouteImport } from './routes/marcas.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AdminGateIndexRouteImport } from './routes/admin/_gate/index'
import { Route as AdminGateSeoRouteImport } from './routes/admin/_gate/seo'
import { Route as AdminGateBlogIndexRouteImport } from './routes/admin/_gate/blog.index'
import { Route as AdminGateBlogSlugRouteImport } from './routes/admin/_gate/blog.$slug'
import { Route as AdminGatePaginasIndexRouteImport } from './routes/admin/_gate/paginas.index'
import { Route as AdminGateBlogPreviewSlugRouteImport } from './routes/admin/_gate/blog.preview.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/$brandSlug',
  path: '/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRoute = AdminGateRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSplatRoute = CatalogoSplatRouteImport.update({
  id: '/catalogo/$',
  path: '/catalogo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoTabacoRoute = ConteudoTabacoRouteImport.update({
  id: '/conteudo/tabaco',
  path: '/conteudo/tabaco',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadeRoute = LegalPrivacidadeRouteImport.update({
  id: '/legal/privacidade',
  path: '/legal/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermosRoute = LegalTermosRouteImport.update({
  id: '/legal/termos',
  path: '/legal/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasIndexRoute = MarcasIndexRouteImport.update({
  id: '/marcas/',
  path: '/marcas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasSlugRoute = MarcasSlugRouteImport.update({
  id: '/marcas/$slug',
  path: '/marcas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateIndexRoute = AdminGateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateSeoRoute = AdminGateSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBlogIndexRoute = AdminGateBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBlogSlugRoute = AdminGateBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGatePaginasIndexRoute = AdminGatePaginasIndexRouteImport.update({
  id: '/paginas/',
  path: '/paginas/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBlogPreviewSlugRoute =
  AdminGateBlogPreviewSlugRouteImport.update({
    id: '/blog/preview/$slug',
    path: '/blog/preview/$slug',
    getParentRoute: () => AdminGateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acessorios': typeof AcessoriosRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$': typeof CatalogoSplatRoute
  '/conteudo/tabaco': typeof ConteudoTabacoRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/admin/seo': typeof AdminGateSeoRoute
  '/admin/': typeof AdminGateIndexRoute
  '/admin/blog/$slug': typeof AdminGateBlogSlugRoute
  '/admin/blog/': typeof AdminGateBlogIndexRoute
  '/admin/paginas/': typeof AdminGatePaginasIndexRoute
  '/admin/blog/preview/$slug': typeof AdminGateBlogPreviewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acessorios': typeof AcessoriosRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$': typeof CatalogoSplatRoute
  '/conteudo/tabaco': typeof ConteudoTabacoRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/blog': typeof BlogIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/marcas': typeof MarcasIndexRoute
  '/admin/seo': typeof AdminGateSeoRoute
  '/admin': typeof AdminGateIndexRoute
  '/admin/blog/$slug': typeof AdminGateBlogSlugRoute
  '/admin/blog': typeof AdminGateBlogIndexRoute
  '/admin/paginas': typeof AdminGatePaginasIndexRoute
  '/admin/blog/preview/$slug': typeof AdminGateBlogPreviewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acessorios': typeof AcessoriosRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/_gate': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogo/$': typeof CatalogoSplatRoute
  '/conteudo/tabaco': typeof ConteudoTabacoRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/termos': typeof LegalTermosRoute
  '/marcas/$slug': typeof MarcasSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/admin/_gate/seo': typeof AdminGateSeoRoute
  '/admin/_gate/': typeof AdminGateIndexRoute
  '/admin/_gate/blog/$slug': typeof AdminGateBlogSlugRoute
  '/admin/_gate/blog/': typeof AdminGateBlogIndexRoute
  '/admin/_gate/paginas/': typeof AdminGatePaginasIndexRoute
  '/admin/_gate/blog/preview/$slug': typeof AdminGateBlogPreviewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$brandSlug'
    | '/acessorios'
    | '/busca'
    | '/contato'
    | '/faq'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/catalogo/$'
    | '/conteudo/tabaco'
    | '/legal/aviso-legal'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/blog/'
    | '/catalogo/'
    | '/marcas/'
    | '/admin/seo'
    | '/admin/'
    | '/admin/blog/$slug'
    | '/admin/blog/'
    | '/admin/paginas/'
    | '/admin/blog/preview/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$brandSlug'
    | '/acessorios'
    | '/busca'
    | '/contato'
    | '/faq'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/login'
    | '/blog/$slug'
    | '/catalogo/$'
    | '/conteudo/tabaco'
    | '/legal/aviso-legal'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/blog'
    | '/catalogo'
    | '/marcas'
    | '/admin/seo'
    | '/admin'
    | '/admin/blog/$slug'
    | '/admin/blog'
    | '/admin/paginas'
    | '/admin/blog/preview/$slug'
  id:
    | '__root__'
    | '/'
    | '/$brandSlug'
    | '/acessorios'
    | '/busca'
    | '/contato'
    | '/faq'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/_gate'
    | '/admin/login'
    | '/blog/$slug'
    | '/catalogo/$'
    | '/conteudo/tabaco'
    | '/legal/aviso-legal'
    | '/legal/privacidade'
    | '/legal/termos'
    | '/marcas/$slug'
    | '/produto/$slug'
    | '/blog/'
    | '/catalogo/'
    | '/marcas/'
    | '/admin/_gate/seo'
    | '/admin/_gate/'
    | '/admin/_gate/blog/$slug'
    | '/admin/_gate/blog/'
    | '/admin/_gate/paginas/'
    | '/admin/_gate/blog/preview/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandSlugRoute: typeof BrandSlugRoute
  AcessoriosRoute: typeof AcessoriosRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AdminGateRoute: typeof AdminGateRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CatalogoSplatRoute: typeof CatalogoSplatRoute
  ConteudoTabacoRoute: typeof ConteudoTabacoRoute
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalPrivacidadeRoute: typeof LegalPrivacidadeRoute
  LegalTermosRoute: typeof LegalTermosRoute
  MarcasSlugRoute: typeof MarcasSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  MarcasIndexRoute: typeof MarcasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brandSlug': {
      id: '/$brandSlug'
      path: '/$brandSlug'
      fullPath: '/$brandSlug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$': {
      id: '/catalogo/$'
      path: '/catalogo/$'
      fullPath: '/catalogo/$'
      preLoaderRoute: typeof CatalogoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/tabaco': {
      id: '/conteudo/tabaco'
      path: '/conteudo/tabaco'
      fullPath: '/conteudo/tabaco'
      preLoaderRoute: typeof ConteudoTabacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidade': {
      id: '/legal/privacidade'
      path: '/legal/privacidade'
      fullPath: '/legal/privacidade'
      preLoaderRoute: typeof LegalPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/termos': {
      id: '/legal/termos'
      path: '/legal/termos'
      fullPath: '/legal/termos'
      preLoaderRoute: typeof LegalTermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/': {
      id: '/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof MarcasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/$slug': {
      id: '/marcas/$slug'
      path: '/marcas/$slug'
      fullPath: '/marcas/$slug'
      preLoaderRoute: typeof MarcasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate/': {
      id: '/admin/_gate/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminGateIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/seo': {
      id: '/admin/_gate/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminGateSeoRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/blog/': {
      id: '/admin/_gate/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminGateBlogIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/blog/$slug': {
      id: '/admin/_gate/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/admin/blog/$slug'
      preLoaderRoute: typeof AdminGateBlogSlugRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/paginas/': {
      id: '/admin/_gate/paginas/'
      path: '/paginas'
      fullPath: '/admin/paginas/'
      preLoaderRoute: typeof AdminGatePaginasIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/blog/preview/$slug': {
      id: '/admin/_gate/blog/preview/$slug'
      path: '/blog/preview/$slug'
      fullPath: '/admin/blog/preview/$slug'
      preLoaderRoute: typeof AdminGateBlogPreviewSlugRouteImport
      parentRoute: typeof AdminGateRoute
    }
  }
}

interface AdminGateRouteChildren {
  AdminGateSeoRoute: typeof AdminGateSeoRoute
  AdminGateIndexRoute: typeof AdminGateIndexRoute
  AdminGateBlogSlugRoute: typeof AdminGateBlogSlugRoute
  AdminGateBlogIndexRoute: typeof AdminGateBlogIndexRoute
  AdminGatePaginasIndexRoute: typeof AdminGatePaginasIndexRoute
  AdminGateBlogPreviewSlugRoute: typeof AdminGateBlogPreviewSlugRoute
}

const AdminGateRouteChildren: AdminGateRouteChildren = {
  AdminGateSeoRoute: AdminGateSeoRoute,
  AdminGateIndexRoute: AdminGateIndexRoute,
  AdminGateBlogSlugRoute: AdminGateBlogSlugRoute,
  AdminGateBlogIndexRoute: AdminGateBlogIndexRoute,
  AdminGatePaginasIndexRoute: AdminGatePaginasIndexRoute,
  AdminGateBlogPreviewSlugRoute: AdminGateBlogPreviewSlugRoute,
}

const AdminGateRouteWithChildren = AdminGateRoute._addFileChildren(
  AdminGateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandSlugRoute: BrandSlugRoute,
  AcessoriosRoute: AcessoriosRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AdminGateRoute: AdminGateRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  CatalogoSplatRoute: CatalogoSplatRoute,
  ConteudoTabacoRoute: ConteudoTabacoRoute,
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalPrivacidadeRoute: LegalPrivacidadeRoute,
  LegalTermosRoute: LegalTermosRoute,
  MarcasSlugRoute: MarcasSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  MarcasIndexRoute: MarcasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
